name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  go:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.23.x, 1.24.x]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - run: make test
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.x
          cache: true
      - uses: golangci/golangci-lint-action@v8
        with:
          version: latest
